version: "3.9"

services:
    database:
        image: postgres
        container_name: moncashback
        restart: always
        ports: 
            - 5434:5432
        environment:
            - POSTGRES_USER=moncashback
            - POSTGRES_PASSWORD=qwe123
            - POSTGRES_DB=moncashback
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        ports: 
            - 6379:6379

    # app:
    #     build: .
    #     container_name: moncashback
    #     restart: always
    #     ports: 
    #         - 3333:3333
    #         - 9229:9229
    #     volumes: 
    #         - .:/usr/app


volumes:
    pgdata:
        driver: local